"""init

Revision ID: 043579a85fed
Revises: 
Create Date: 2025-10-01 12:10:05.483937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043579a85fed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('artiste',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('style', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('concert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('lieu', sa.String(length=100), nullable=True),
    sa.Column('artiste_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artiste_id'], ['artiste.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_client', sa.String(length=100), nullable=True),
    sa.Column('email_client', sa.String(length=100), nullable=True),
    sa.Column('presence', sa.Boolean(), nullable=True),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('concert')
    op.drop_table('artiste')
    op.drop_table('admin')
    # ### end Alembic commands ###
